# Generated by Django 4.0.1 on 2022-01-18 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=30)),
                ('registration_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.vehicle'),
        ),
    ]
